In [1]:
import pandas as pd
import folium

In [2]:
data = pd.read_csv('Users.csv')

In [15]:
data.head(1)

  UserID  Age Gender Country SubscriptionStatus  TotalWatchTime  Device
0   SF_1   11      F   India               Free             231  Mobile

In [7]:
geo_data = data[["Country","UserID"]].groupby(by = data["Country"]).agg(total_usr = ("UserID", 'count'))

In [23]:
geo_data = geo_data.reset_index()

In [24]:
geo_data.head(5)

  Country  total_usr
0  Canada       1034
1  France        986
2   India       1021
3   Italy       1016
4      UK        961

In [11]:
world_map_json = 'https://raw.githubusercontent.com/python-visualization/folium/main/examples/data/world-countries.json'

In [42]:
# Create a base world map
m = folium.Map(location=[20, 0], zoom_start=2, tiles="CartoDB positron")

c:\Users\edmon\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\folium\raster_layers.py:130: UserWarning: CartoDB tiles now require an API key. Please provide one to continue using the tiles. You can request the key at https://carto.com/basemaps/apikey/.
  tiles = tiles.build_url(fill_subdomain=False, scale_factor="{r}")  # type: ignore

In [32]:
folium.Choropleth(
    geo_data=world_map_json,
    name="choropleth",
    data=geo_data,
    columns=["Country", "total_usr"],
    key_on="feature.properties.name",  # Maps your country names to GeoJSON names
    fill_color="YlOrRd",  # Colour scale: Yellow -> Orange -> Red
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Number of User IDs",
).add_to(m)

folium.LayerControl().add_to(m)

In [ ]:
m.save("country_user_heatmap.html")

In [37]:
import plotly.express as px

In [41]:
fig = px.choropleth(
    geo_data,
    locations="Country",  # Country column
    locationmode="country names",  # Match by standard country names
    color="total_usr",  # Column to shade by
    color_continuous_scale="Reds",  # Heatmap color scheme
    title="User Distribution by Country",
)

# Open directly inside Jupyter notebook/EDA cell
fig.show(renderer="browser")